// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coooousruuxvofgoatub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvb29vdXNydXV4dm9mZ29hdHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2MjYyODksImV4cCI6MjA5MzIwMjI4OX0.4U93cqfulTavMbblQIzuuUQaY5nFQJUCVhZ_o1BKwJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});